- content/uxp/install.md
We are working with AWS to provide `uxp` as an EKS Addon. The `uxp` installation has been tailored to fit AWS requirements and the `crossplane-rbac-manager` has been disabled for the installation. 
This means that in order to install and use any provider, customers will need to configure `uxp` by granting additional cluster scope permissions to the `crossplane` pod and `providers` pods.
This PR shows how to perform such configuration using imperative commands.
> This instructions will no longer be needed whenl AWS allows the use of `crossplane-rbac-manager`.
Fixes https://github.com/upbound/platform-core/issues/557
I have:
Locally with `hugo server`
> Configure uxp when installed as an EKS Addon

- content/uxp/install.md
UXP is not an EKS add-on (that is reserved for AWS add-ons, I believe), so it's better to frame as "installing from the EKS management console" to align with language used in the blog.
Signed-off-by: Craig D Wilhite <cdwilhite0601@gmail.com>
> Change wording from "eks add-on"

- content/quickstart/quickstart-common.md
- content/uxp/_index.md
- content/uxp/install.md
- content/uxp/upgrade.md
Updating docs to reflect `xgql` removal from UXP 1.11 as per https://github.com/upbound/universal-crossplane/pull/327.
I have:
N.A.
> docs: removed xgql and fixed bootstrapper references

- content/upbound-marketplace/packages.md
Makes a few updates to the documentation for publishing packages to the Upbound Marketplace.
- explain repo visibility and default visibility for new repos 
- add recommended metadata annotations for `crossplane.yaml` per the xpkg specification to ensure listings render with all key information
- update documentation for a one-time approval process before public packages get published (we have a repo-level publishing policy instead of changing the visibility).
I have:
Ran `hugo server` locally.
> Update package publishing documentation

- themes/upbound/layouts/partials/head/base.html
- themes/upbound/layouts/partials/head/favicons.html
The partial for favicons was commented out. This re-enables it.
> [staging] Re-enable favicons partial

- content/knowledge-base/git-integration.md
Account is not the user-account. Our docs use account and users interchangeably. Hence, make clear that this is the org.
> knowledge-base: clarify what the account for an MXP is

- content/knowledge-base/lifecycle.md
Goal to explain our support lifecycle. Have a few inflight contracts that want express understanding of what we support.
> add GA lifecycle docs

- content/knowledge-base/migrate-to-provider-families.md
Fixes: #154 
This PR adds a section that tells to activate the family resource providers in the configuration migration guide for provider families.
> Add a section in family providers migration guide to activate resoures provider revisions

- content/cli/command-reference.md
As a result of https://github.com/upbound/squad-upbound-cloud/issues/1265, an immediate action was to be more specific about the current state of token usage in Upbound in our docs.
Long-term, we should design for using service accounts instead of personal credentials.
`hugo server` locally to ensure everything renders correctly, including the relref.
> More explicit documentation about PAT vs robot tokens

- content/upbound-marketplace/packages.md
This has disappeared in later versions than v0.10, and hence gives a 404.
Alternative: readd the xpkg docs in latest Crossplane docs.
> upbound-marketplace: fix link to xpkg reference

- themes/upbound/assets/scss/_color-mode-dark.scss
- themes/upbound/assets/scss/_color-mode-light.scss
previous gray snippet backgrounds would not appear when placed on colored backgrounds, such as hints
this fixes that issue by changing the background to be opacity-based
> adjusted code snippets to work with non-white bgs

- themes/upbound/layouts/partials/body/left-sidebar-nav.html
Modified the side nav template to support nested (and collapsible) subheaders. For this to actually display, we'll just need to nest directories under any of the existing directories under `/content`. Until then, there will be no visual changes seen in the Docs page.
We're expecting to add nested content next week.
**Example (with dummy content)**
> Collapsible nav headers

- content/xp-arch-framework/_index.md
- content/xp-arch-framework/architecture/_index.md
- content/xp-arch-framework/architecture/architecture-baseline-multi.md
- content/xp-arch-framework/architecture/architecture-baseline-single.md
- content/xp-arch-framework/building-apis/_index.md
- content/xp-arch-framework/building-apis/building-apis-compositions.md
- content/xp-arch-framework/building-apis/building-apis-configurations.md
- content/xp-arch-framework/building-apis/building-apis-xrds.md
- content/xp-arch-framework/interface-integrations/_index.md
- content/xp-arch-framework/interface-integrations/git-and-gitops.md
- content/xp-arch-framework/interface-integrations/monitoring-and-observability.md
- content/xp-arch-framework/interface-integrations/platform-continuity.md
- content/xp-arch-framework/interface-integrations/platform-frontends.md
- content/xp-arch-framework/interface-integrations/policy-engines.md
- content/xp-arch-framework/interface-integrations/secrets-management.md
- utils/vale/styles/Google/Headings.yml
- utils/vale/styles/Microsoft/HeadingAcronyms.yml
- utils/vale/styles/Microsoft/Terms.yml
- utils/vale/styles/Upbound/spelling-exceptions.txt
- utils/vale/styles/gitlab/CurlStringsQuoted.yml
- utils/vale/styles/gitlab/MeaningfulLinkWords.yml
- utils/vale/styles/gitlab/Uppercase.yml
We merged the xp-arch-framework content without fixing the vale warnings around spelling and voicing. I've fixed all of them in this PR.
> Fix vale warnings for xp-arch-framework content

- postcss.config.js
- themes/upbound/layouts/partials/head/base.html
While testing some fixes for the img shortcode I noticed that we cache the production optimized stylesheet. Since the stylesheet is dynamically generated it can cause the cache reference to be wrong.
This PR removes caching of the stylesheet in hugo and adds an improvement for CSS optimization with PostCSS
> Fix CSS Caching

- content/contribute/features.md
- content/quickstart/aws-deploy.md
- content/quickstart/azure-deploy.md
- content/quickstart/gcp-deploy.md
- themes/upbound/layouts/shortcodes/img.html
`img` shortcode was effectively disabled at launch time. This turns the img shortcode back on and applies some image fixes to the quickstart. 
Visual inspection of other pages looked like quality was good and images didn't need adjusting. 
> Fix img shortcode

- themes/upbound/assets/scss/_left-sidebar-nav.scss
The left-nav scroll is causing UI issues on systems that have scrollbars displayed by default. Will disable this on Prod while working on a fix.
> Temporarily disable left-nav scroll

- themes/upbound/assets/scss/_left-sidebar-nav.scss
- themes/upbound/assets/scss/_right-sidebar-toc.scss
- themes/upbound/assets/scss/bootstrap/_list-group.scss
- Use underline instead of color for right nav anchor link hover
- Remove purple pressed state for left nav pages that resulted in a gray>purple>gray>purple flicker
> Update Right Nav Hover State & Fix Left Nav Pressed State

- content/providers/provider-aws/_index.md
- content/providers/provider-aws/authentication.md
- content/providers/releases.md
- utils/vale/styles/Google/Headings.yml
This adds official documentation covering all supported authentication methods for OP AWS.
This also creates a new section for the specific AWS provider and moves the AWS release notes to the AWS provider page. 
@jeanduplessis let me know if you're okay with this approach for release notes. 
@ulucinar can you review for technical accuracy? I manually tested everything but let me know if I've made any mistakes or missed something. 
> Add AWS authentication docs

- content/providers/provider-aws/authentication.md
- utils/vale/styles/Google/WordList.yml
Corrects a mistake that the pod name was used to check for IAM auth. It's the `ServiceAccount` name that's used. 
> Update that the provider SA is used for auth not pod name

- content/concepts/managed-control-planes.md
Updated MCP concept docs under "create flows" to describe how to create a control plane with provider-upbound. We still need to add additional docs on the marketplace for the provider (explanations for configuring the providerconfig of the provider, etc). Marketplace is the right home for these sorts of docs.
> Add content explaining how to create a control plane using provider-upbound

- content/providers/provider-gcp/_index.md
- content/providers/provider-gcp/authentication.md
- utils/vale/styles/Google/Headings.yml
- utils/vale/styles/Google/WordList.yml
Details the authentication methods supported by OP GCP. Breaks release notes out into a dedicated page. 
> Provider GCP Auth docs

- content/reference/cli/_index.md
add an alias to redirect original CLI url to avoid breaking google results
> add an alias to redirect original CLI URL

- content/spaces/observability.md
This removes the servicemonitors for kube-state-metrics and mxp-gateway. The control-plane KSM doesn't have any metrics useful outside of billing, and mxp-gateway should be getting scraped by otlp-collector.
There are also some minor changes for readability.
> Observability doc fixes

- content/spaces/observability.md
This fixes example mxp-gateway metrics queries to work with Spaces v1.0.1.
> Fix mxp-gateway metrics examples

- content/spaces/_index.md
The cards on the docs index site go to the _index.md page for each section. The spaces page is empty, leading the user to a blank page. 
This copies the `overview` page into _index.md so there's some content, but we should probably have a better solution in the long run.
> add content for Spaces index page

- content/spaces/_index.md
- themes/upbound/layouts/partials/head/base.html
The title for the docs that shows up in a tab today just says "Upbound docs". This adds the page name as well so you can tell one tab from another. 
> add content for index page

- content/contribute/vale.md
The current commands have a trailing backtick which results in the command being quoted in a terminal.
> Fix vale commands so that copy and paste works

- content/upbound-marketplace/packages.md
Per request, not routing community members through support if they need assistance to publish a package.
> Remove support e-mail for community contributions

- content/providers/provider-azure/authentication.md
Add steps for configuring an Azure service principal with client certificate authentication in Azure provider.
Should be merged in sync with feature PR in the Azure provider.
> Azure provider service principal authentication with client certificates

- content/providers/migration.md
Plus some small things automatically fixed by Vale.
> Add a warning about management policies overriding deletionPolicy to the provider family migration guide

- content/providers/provider-aws/_index.md
This PR fixes wrong links in the latest release info for provider aws.
> Fix links in the latest release info for provider aws

- content/spaces/quickstart/aws-deploy.md
- content/spaces/quickstart/azure-deploy.md
- content/spaces/quickstart/gcp-deploy.md
This PR updates the quick start guides for Spaces on cloud providers:
- Updates UXP version and configuration parameters.
- Update provider-kubernetes and provider-helm versions.
- Uses `DeploymentRuntimeConfig` instead of deprecated `ControllerConfig`.
> Update Spaces quickstart for cloud providers

- content/reference/rel-notes.md
This PR adds release notes for control plane connector starting with the most recent 3 releases.
> Add release notes for control plane connector

- content/reference/lifecycle.md
The "up to 12 months" sounded like a promise, and with that it was contradicting the individual support time frame definition further town, especially UXP with only -2 UXP releases, not -3.
> lifecycle: clarify time span of support

- content/spaces/observability.md
Replace v1 observability docs with guidance for enabling the new version of the feature, which only requires config to export to a designated otel collector exporter
> Document new observability pipeline feature

- content/providers/provider-aws/authentication.md
This PR https://github.com/upbound/docs/pull/272 updated from `ControllerConfig` named `irsa-controllerconfig ` to `DeploymentRuntimeConfig` named `irsa-runtimeconfig `.
There is one reference that wasn't updated. Fixing that here.
> Update AWS authentication.md runtimeConfigRef name

- content/spaces/observability.md
Replaces the POC Observability docs with the current [SharedTelmetryConfig](https://github.com/upbound/spaces/pull/876) approach.
> update Observability with SharedTelemetryConfig
