upbound/docs

static/index.html
themes/hugo-geekdoc/layouts/_default/baseof.html
themes/hugo-geekdoc/layouts/partials/product-nav.html
themes/hugo-geekdoc/layouts/partials/site-header.html
themes/hugo-geekdoc/static/custom.css

Reworked top nav and update links

rework top nav

---

themes/hugo-geekdoc/layouts/partials/site-footer.html
themes/hugo-geekdoc/static/custom.css

Add css to allow footer responsiveness on smaller screen sizes
Fixes
https://upbound-unomena.atlassian.net/browse/UP-105

footer responsiveness

---

themes/hugo-geekdoc/assets/styles/custom.css
themes/hugo-geekdoc/layouts/404.html

Add 404 pages

---

.github/workflows/link-checker.yml
utils/htmltest/.htmltest.yml

Add link checking github action

---

.github/workflows/build-hugo-templates.yml
.github/workflows/vale.yml

Add Vale and manual Hugo Build workflows

---

themes/upbound/layouts/partials/head/meta-common.html

Adds a meta tag to prove to bing we own the site.

Add bing site auth meta tag

---

content/knowledge-base/lifecycle.md
utils/vale/styles/Microsoft/HeadingAcronyms.yml
utils/vale/styles/Upbound/spelling-exceptions.txt
utils/vale/styles/write-good/Weasel.yml

fix vale errors in new lifecycle page

---

themes/upbound/assets/scss/_hints.scss

- Switches Tips to be blue and Notes to be gray
- Color updates (color codes and full-colored-borders)
- Spacing updates

Hints design

---

themes/upbound/assets/scss/_code-theme.scss
themes/upbound/assets/scss/_home.scss
themes/upbound/assets/scss/_variables.scss
themes/upbound/layouts/shortcodes/img.html

- Add border-radius to code blocks and correct border-radius for images
- Minor typography updates

Border-radius and Typography minor updates

---

themes/upbound/layouts/_default/baseof.html
themes/upbound/layouts/partials/body/gtag-body.html
themes/upbound/layouts/partials/head/base.html
themes/upbound/layouts/partials/head/js/gtag-header.html

Add google tag manager tags

---

themes/upbound/assets/scss/_code-theme.scss
themes/upbound/assets/scss/_color-mode-dark.scss
themes/upbound/assets/scss/_color-mode-light.scss
themes/upbound/assets/scss/_color-modes.scss

This also moves the body rule out of the code-theme mixin.

Add selection background color

---

content/xp-arch-framework/self-eval.md
utils/vale/styles/Microsoft/HeadingAcronyms.yml
utils/vale/styles/Upbound/spelling-exceptions.txt
utils/vale/styles/gitlab/Uppercase.yml

PR didnt pick up 2nd commit so reopening a new one (sorry for spam)

overhaul self-eval

---

themes/upbound/assets/scss/_home.scss
themes/upbound/assets/scss/_right-sidebar-toc.scss

- home page Learn links
- right nav anchor links

Add hover states to various doc elements

---

content/providers/releases.md
content/providers/support.md
utils/vale/.vale.ini

Adds a releases page for the Upbound Official providers.

Add provider releases page

---

content/providers/releases.md

Adds the releases page for the Upbound Official providers.

Update provider releases page

---

themes/upbound/assets/scss/_code-theme.scss

Fix added/removed line colors in code blocks

---

content/reference/cli/command-reference.md
content/reference/rel-notes.md
content/spaces/overview.md
content/spaces/quickstart/aws-deploy.md
content/spaces/quickstart/azure-deploy.md
content/spaces/quickstart/gcp-deploy.md
content/spaces/quickstart/kind-deploy.md

This bumps version references and adds release notes.

Update Spaces docs for v1.0.1

---

content/providers/provider-families.md

Adds note for provider family dependency resolution and explains version mismatch.

Add note for provider family dependency resolution

---

content/xp-arch-framework/interface-integrations/git-and-gitops.md

user reported a broken link they found from google. 
The original content was broken up and moved, this is the next best home for it.

add redirect for broken link

---

content/providers/provider-azure/authentication.md

This PR attempts to address #209.
I've added more context around the secret auth & system-assigned managed identity options. The user-assigned process is not as clear to me so I'm adding a draft here to get some eyes on what I have in the mean time.
Tagging some docs reviewers, as well as the original issue reporter and potential Azure eng help.

Adds Azure Auth Guide

---

content/providers/provider-aws/_index.md
content/providers/provider-azure/_index.md
content/providers/provider-gcp/_index.md

This PR adds new release info for official providers.

Add new release info for official providers

---

content/providers/provider-azuread/_index.md
content/providers/provider-terraform/_index.md

This PR adds release notes for the provider-azuread.

Add release notes for the AzureAD official provider

---

content/spaces/deployment.md

Introduces a small subsection discussing the use of Ingress in Spaces and how to use your own manifest if you choose.

Add a deployment subsection describing bring your own ingress

---

content/concepts/mcp/control-plane-connector.md
content/reference/cli/command-reference.md
content/reference/cli/configuration.md
content/reference/rel-notes.md
content/spaces/_index.md
content/spaces/integrations.md
content/spaces/overview.md
content/spaces/quickstart/aws-deploy.md
content/spaces/quickstart/azure-deploy.md
content/spaces/quickstart/gcp-deploy.md
content/spaces/quickstart/kind-deploy.md
utils/vale/styles/Google/Headings.yml
utils/vale/styles/Upbound/spelling-exceptions.txt

- Bump Spaces quickstart to v1.1.0
- Fixed up some copy/paste flows in quickstart
- Added new documentation for how to use ESO with Spaces
- Added relnotes for Space 1.1
- Documented new CLI commands, re-home some existing ones that got changed

Document and update features for Spaces 1.1

---

content/providers/provider-aws/_index.md

This PR adds new release info for provider-aws.

Add new release info for provider-aws

---

README.md
content/spaces/_index.md
content/spaces/overview.md

small typo fix in some link text destory -> destroy + updated the readme to point to the contributing docs (the other link was 404ing)

fix: small update to link text

---

content/reference/ipaddresses.md

Add page for Upbound infrastructure IP addresses.

IP Addresses: publish IP Addresses for Upbound Infrastructure

---

themes/upbound/layouts/partials/body/left-sidebar-nav.html

Add search element in child item navigation

---

themes/upbound/assets/scss/_right-sidebar-toc.scss
themes/upbound/layouts/partials/body/left-sidebar-nav.html

Add scroll to right nav

---

content/reference/rel-notes.md
content/spaces/_index.md
content/spaces/quickstart/aws-deploy.md
content/spaces/quickstart/azure-deploy.md
content/spaces/quickstart/gcp-deploy.md
content/spaces/quickstart/kind-deploy.md

version update

---

content/quickstart/azure-deploy.md
content/quickstart/multicloud-deploy.md

change Azure Active Directory to Microsoft Entra ID -> https://learn.microsoft.com/en-gb/entra/fundamentals/new-name
fix:
```yaml
before this pr: mcp:$@<your-org>/<your-control-plane-name>$@:provider-provider-azure
after this pr: mcp:$@<your-org>/<your-control-plane-name>$@:provider:provider-azure
```

fix(docs): change Azure Active Directory to Microsoft Entra ID

---

content/spaces/use-argo-flux.md

fix values for argocd setup for spaces

fix(values): fix values for argocd setup for spaces

---

utils/vagrant/Vagrantfile

Updates k8s to v1.29 and fixes new repos and kubeadm config path

---

content/quickstart.md

Fixes the required colon for the azure provider mcp

Fix azure quickstart provider mcp

---

content/spaces/quickstart/_index.md

Update helm install for AKS clusters to reflect annotation to get ingress working. Update instructions for getting IP/name of LB depending on AKS/EKS/GKE

Patch space quickstart

---

content/reference/rel-notes.md
content/spaces/kind-quickstart.md
content/spaces/quickstart/_index.md

This PR add release notes for Space v1.2.4 and bumps the version used in the guides.

Add release notes for Space v1.2.4

---

themes/upbound/assets/scss/_color-mode-light.scss
themes/upbound/assets/scss/_crds.scss
themes/upbound/layouts/partials/body/crds.html

Adds the included default values for configuration items that have them.

add default values

---

content/spaces/helm-reference.md

Adds helm chart configuration values.
Still needs:

Helm Chart configuration values

---

content/providers/provider-aws/authentication.md
utils/vale/styles/Google/Headings.yml

https://github.com/upbound/docs/issues/271

Update AWS authentication.md

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/content.md
.github/ISSUE_TEMPLATE/website.md

update issue template

---

content/reference/cli/rel-notes.md

Very stale docs going back to v0.21.0. Added all the way up to newest v0.29.0 release

Add relnotes for up

---

content/reference/rel-notes.md
content/spaces/kind-quickstart.md
content/spaces/quickstart/_index.md

This change adds the `v1.3.1` patch release notes.

v1.3.1 release notes

---

content/all-spaces/disconnected-spaces/_index.md
content/all-spaces/disconnected-spaces/kind-quickstart.md
content/all-spaces/disconnected-spaces/quickstart/_index.md

This updates the install instructions to importantly enable hub authn/authz. Also updates some wording to Disconnected Spaces / Spaces software

Update Disconnected Space install instructions

---

content/mcp/_index.md

Add alias redirecting concept/mcp -> mcp

Add alias redirecting concept/mcp -> mcp

---

content/all-spaces/disconnected-spaces/backup-and-restore.md
content/all-spaces/disconnected-spaces/billing.md
content/all-spaces/disconnected-spaces/deployment.md
content/all-spaces/disconnected-spaces/helm-reference.md
content/all-spaces/disconnected-spaces/kind-quickstart.md
content/all-spaces/disconnected-spaces/observability.md
content/all-spaces/disconnected-spaces/oidc.md
content/all-spaces/disconnected-spaces/quickstart/_index.md
content/all-spaces/disconnected-spaces/secrets-management.md
content/all-spaces/disconnected-spaces/spaces-management.md
content/all-spaces/disconnected-spaces/troubleshooting.md

Add aliases for all old spaces content to point at what's now considered 'disconnected spaces'

Redirect all old spaces content -> disconnected spaces
